//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenDates.WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int id_prod { get; set; }
        public string description { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> stockmin { get; set; }
        public Nullable<int> stockmax { get; set; }
    }
}
