//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenDates.WebServices.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int id_user { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string apelllido { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
