//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoldenDates.WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int id_user { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string nombre { get; set; }
        public string apelllido { get; set; }
        public System.DateTime birthday { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime FechaRegistro { get; set; }
    }
}
